### ISSUE TITLE
Generate the smb tile to use xenial stemcell

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/smb-volume-release#7]

**Comment by HDYA** [comment]
Hi @bingosummer , we should use Xenial stemcell for new release, do you mean we should re-generate existing tiles?

**Comment by bingosummer** [comment]
If no customers ask for it, I think, we don't need to re-generate existing tiles. Will change  the issue tile.

**Comment by julian-hj** [comment]
Since this is purely related to the tile, and nothing to do with this open source bosh release, could we move this discussion to the advertised support link here:
https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade

Apologies if that's not a useful link--it is from the release notes for the tile:
https://network.pivotal.io/products/smb-volume-service/
