### ISSUE TITLE
Cosmetic issues w/marketplace and space name

### ISSUE THREAD

**Issue by opsnative** [cloudfoundry/smb-volume-release#9]
The broker release has some minor cosmetic issues needing cleanup, specifically:

- the system space created has a typo "smb-voloume-service-space" 
- no marketplace icon image within Apps Manager.

Would also suggest leaving the "Default Location" field under the Service Broker Application pane blank (and mandatory). Currently the tile defaults to "useast" which most users overlook and often wish to override (in some circumstances this also causes issue with no Gen4 hardware support in USEast).

**Comment by julian-hj** [comment]
Since this is purely related to the tile, and nothing to do with this open source bosh release, could we move this discussion to the advertised support link here:
https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade

Apologies if that's not a useful link--it is from the release notes for the tile:
https://network.pivotal.io/products/smb-volume-service/

**Comment by HDYA** [comment]
Hi @drhpivotal 

The typo has been fixed in master branch and will reflect to the tile soon. (As we are very to releasing a GA version tile)
Thanks for your advice, making these fields mandatory is a constructive opinion, we'll have a discussion on that along with an icon in Apps Manager.

Wish you all the best,
